const anagrams = [
  {
    word: "alerted",
    solutions: ['alerted', 'altered', 'redealt', 'related', 'treadle', 'dartle', 'dealer',
    'delate',  'derate',  'elated',  'elater',  'laered',  'leader', 'leared',
    'redate',  'redeal',  'relate',  'teared',  'alder',   'alert',  'alter',
    'arede',   'arete',   'arled',   'artel',   'dater',   'dealt',  'deare',
    'delta',   'derat',   'deter',   'eared',   'eater',   'elate',  'elder',
    'lader',   'laree',   'lated',   'later',   'leare',   'leear',  'lered',
    'rated',   'ratel',   'reate',   'relet',   'taler',   'tared',  'teade',
    'teaed',   'telae',   'trade',   'tread',   'treed',   'alee',   'ared',
    'aret',    'arle',    'dale',    'dalt',    'dare',    'dart',   'date',
    'deal',    'dear',    'deer',    'deet',    'dele',    'delt',   'dere',
    'drat',    'dree',    'eale',    'eard',    'earl',    'ered',   'lade',
    'laer',    'lard',    'lare',    'late',    'lead',    'lear',   'leat',
    'leed',    'leer',    'leet',    'lere',    'rade',    'rale',   'rate',
    'read',    'real',    'rede',    'reed',    'reel',    'rete',   'taed',
    'tael',    'tale',    'tare',    'tead',    'teal',    'tear',   'teed',
    'teel',    'teer',    'tela',    'teld',    'tele',    'trad',   'tree',
    'ale',     'alt',     'ard',     'are',     'art',     'ate',    'dae',
    'dal',     'dee',     'del',     'ear',     'eat',     'eel',    'eld',
    'elt',     'era',     'ere',     'eta',     'lad',     'lar',    'lat',
    'lea',     'led',     'lee',     'let',     'rad',     'rat',    'red',
    'ree',     'ret',     'tad',     'tae',     'tar',     'tea',    'ted',
    'tee',     'tel'],
  },
  {
    word: "aridest",
    solutions: [
      'aridest', 'asterid', 'astride', 'diaster', 'disrate', 'staider', 'staired',
  'tardies', 'tirades', 'aiders',  'airest',  'airted',  'arties',  'daters',
  'deairs',  'derats',  'direst',  'driest',  'irades',  'raised',  'raited',
  'redias',  'resaid',  'saired',  'satire',  'stared',  'steard',  'stired',
  'striae',  'stride',  'terais',  'tirade',  'trades',  'treads',  'triads',
  'adits',   'aesir',   'aider',   'aides',   'aired',   'airts',   'arets',
  'arise',   'arsed',   'artis',   'aside',   'aster',   'astir',   'dares',
  'daris',   'darts',   'dater',   'dates',   'deair',   'dears',   'deist',
  'derat',   'diets',   'dirts',   'ditas',   'dites',   'drats',   'drest',
  'dries',   'eards',   'earst',   'edits',   'ideas',   'irade',   'irate',
  'raids',   'raise',   'raits',   'rased',   'rated',   'rates',   'reads',
  'reast',   'redia',   'reist',   'resat',   'resid',   'resit',   'retia',
  'riads',   'rides',   'rites',   'sared',   'sated',   'serai',   'sider',
  'sired',   'sitar',   'sited',   'stade',   'staid',   'stair',   'stare',
  'stead',   'stear',   'stied',   'stire',   'strad',   'strae',   'stria',
  'tared',   'tares',   'tarsi',   'taser',   'teads',   'tears',   'terai',
  'teras',   'tiars',   'tides',   'tiers',   'tired',   'tires',   'trade',
  'trads',   'tread',   'triad',   'tride',   'tried',   'tries',   'tsade',
  'tsadi',   'adit',    'aide',    'aids',    'airs',    'airt',    'aits',
  'ards',    'ared',    'ares',    'aret',    'arid',    'aris',    'arse',
  'arti',    'arts',    'ates',    'daes',    'dais',    'dare',    'dari',
  'dart',    'date',    'dear',    'desi',    'dies',    'diet',    'dire',
  'dirt',    'disa',    'dita',    'dite',    'dits',    'drat',    'eard',
  'ears',    'east',    'eats',    'edit',    'eras',    'erst',    'etas',
  'idea',    'ides',    'ired',    'ires',    'itas',    'rade',    'rads',
  'raid',    'rais',    'rait',    'rase',    'rast',    'rate',    'rats',
  'read',    'reds',    'reis',    'rest',    'rets',    'riad',    'rias',
  'ride',    'rids',    'rise',    'rite',    'rits',    'sade',    'sadi',
  'said',    'sair',    'sard',    'sari',    'sate',    'sati',    'sear',
  'seat',    'seir',    'sera',    'seta',    'sida',    'side',    'sire',
  'site',    'star',    'sted',    'stie',    'stir',    'tads',    'taed',
  'taes',    'tais',    'tare',    'tars',    'tead',    'tear',    'teas',
  'teds',    'tiar',    'tide',    'tids',    'tied',    'tier',    'ties',
  'tire',    'trad',    'tres',    'trie',    'tsar',    'ads',     'aid',
  'air',     'ais',     'ait',     'ard',     'are',     'ars',     'art',
  'ate',     'ats',     'dae',     'das',     'dei',     'die',     'dis',
  'dit',     'ear',     'eas',     'eat',     'eds',     'era',     'ers',
  'est',     'eta',     'ide',     'ids',     'ire',     'ita',     'its',
  'rad',     'rai',     'ras',     'rat',     'red',     'rei',     'res',
  'ret',     'ria',     'rid',     'rit',     'sad',     'sae',     'sai',
  'sar',     'sat',     'sea',     'sed',     'sei',     'ser',     'set',
  'sir',     'sit',     'sri',     'tad',     'tae',     'tai',     'tar',
  'tas',     'tea',     'ted',     'tes',     'tid',     'tie',     'tis'
    ],
  },
  {
    word:"aspired",
    solutions:[
      'aspired', 'despair', 'diapers', 'praised', 'aiders', 'aspire', 'deairs',
      'diaper',  'drapes',  'irades',  'padres',  'paired', 'paires', 'pardie',
      'paries',  'parsed',  'perais',  'praise',  'prides', 'prised', 'raised',
      'rapids',  'rasped',  'redias',  'redips',  'repaid', 'resaid', 'risped',
      'saired',  'spader',  'spared',  'sparid',  'spider', 'spirea', 'spired',
      'spraid',  'spread',  'aesir',   'aider',   'aides',  'aired',  'apers',
      'apres',   'arise',   'arsed',   'aside',   'asper',  'dares',  'daris',
      'deair',   'dears',   'drape',   'draps',   'dries',  'drips',  'eards',
      'epris',   'ideas',   'irade',   'padis',   'padre',  'padri',  'paire',
      'pairs',   'paise',   'pardi',   'pards',   'pared',  'pares',  'paris',
      'parse',   'pears',   'perai',   'peris',   'piers',  'prads',  'prase',
      'presa',   'pride',   'pried',   'pries',   'prise',  'raids',  'raise',
      'raped',   'rapes',   'rapid',   'rased',   'reads',  'reaps',  'redia',
      'redip',   'resid',   'riads',   'rides',   'riped',  'ripes',  'sapid',
      'sared',   'sepad',   'sepia',   'serai',   'sider',  'siped',  'sired',
      'spade',   'spaed',   'spaer',   'spard',   'spare',  'spear',  'speir',
      'spide',   'spied',   'spier',   'spire',   'sprad',  'spred',  'aide',
      'aids',    'airs',    'aped',    'aper',    'apes',   'apse',   'ards',
      'ared',    'ares',    'arid',    'aris',    'arse',   'daes',   'dais',
      'daps',    'dare',    'dari',    'dear',    'desi',   'dies',   'dips',
      'dire',    'disa',    'drap',    'drip',    'eard',   'ears',   'eras',
      'idea',    'ides',    'ired',    'ires',    'padi',   'pads',   'paid',
      'pair',    'pais',    'pard',    'pare',    'pars',   'pase',   'pear',
      'peas',    'peds',    'peri',    'pias',    'pied',   'pier',   'pies',
      'pirs',    'pise',    'prad',    'rade',    'rads',   'raid',   'rais',
      'rape',    'raps',    'rase',    'rasp',    'read',   'reap',   'reds',
      'reis',    'reps',    'riad',    'rias',    'ride',   'rids',   'ripe',
      'rips',    'rise',    'risp',    'sade',    'sadi',   'said',   'sair',
      'sard',    'sari',    'sear',    'seir',    'sera',   'sida',   'side',
      'sipe',    'sire',    'spae',    'spar',    'sped',   'spie',   'ads',
      'aid',     'air',     'ais',     'ape',     'ard',    'are',    'ars',
      'asp',     'dae',     'dap',     'das',     'dei',    'die',    'dip',
      'dis',     'ear',     'eas',     'eds',     'era',    'ers',    'ide',
      'ids',     'ire',     'pad',     'par',     'pas',    'pea',    'ped',
      'per',     'pes',     'pia',     'pie',     'pir',    'pis',    'pre',
      'psi',     'rad',     'rai',     'rap',     'ras',    'red',    'rei',
      'rep',     'res',     'ria',     'rid',     'rip',    'sad',    'sae',
      'sai',     'sap',     'sar',     'sea',     'sed',    'sei',    'ser',
      'sip',     'sir',     'spa',     'sri'
    ]
  },{
    word:"canters",
    solutions:['canters', 'carnets', 'nectars', 'recants', 'scanter', 'tanrecs', 'trances',
    'antres',  'ascent',  'astern',  'caners',  'canter',  'carets',  'carnet',
    'cartes',  'casern',  'caster',  'caters',  'centas',  'centra',  'cranes',
    'crants',  'crates',  'creant',  'crenas',  'cresta',  'enacts',  'nacres',
    'nectar',  'rances',  'reacts',  'recant',  'recast',  'secant',  'stance',
    'sterna',  'tanrec',  'traces',  'trance',  'transe',  'acers',   'acnes',
    'acres',   'antes',   'antre',   'arets',   'aster',   'caner',   'canes',
    'canst',   'cants',   'cares',   'caret',   'carns',   'carse',   'carte',
    'carts',   'caste',   'cater',   'cates',   'cents',   'certs',   'cesta',
    'crane',   'crans',   'crate',   'crena',   'crest',   'earns',   'earst',
    'enact',   'escar',   'etnas',   'nacre',   'narcs',   'nares',   'nates',
    'nears',   'neats',   'nerts',   'races',   'rance',   'rants',   'rates',
    'react',   'reans',   'reast',   'recta',   'rents',   'resat',   'saner',
    'scant',   'scare',   'scart',   'sceat',   'scena',   'scent',   'scrae',
    'scran',   'scrat',   'serac',   'snare',   'stane',   'stare',   'starn',
    'stean',   'stear',   'stern',   'strae',   'taces',   'tares',   'tarns',
    'taser',   'tears',   'teras',   'terns',   'trace',   'trans',   'acer',
    'aces',    'acne',    'acre',    'acts',    'aesc',    'ance',    'anes',
    'ante',    'ants',    'arcs',    'ares',    'aret',    'arse',    'arts',
    'ates',    'cane',    'cans',    'cant',    'care',    'carn',    'cars',
    'cart',    'case',    'cast',    'cate',    'cats',    'ceas',    'cens',
    'cent',    'cert',    'cran',    'eans',    'earn',    'ears',    'east',
    'eats',    'eras',    'erns',    'erst',    'etas',    'etna',    'narc',
    'nare',    'nats',    'near',    'neat',    'nest',    'nets',    'race',
    'rant',    'rase',    'rast',    'rate',    'rats',    'rean',    'recs',
    'rens',    'rent',    'rest',    'rets',    'sane',    'sant',    'sate',
    'scan',    'scar',    'scat',    'sean',    'sear',    'seat',    'sect',
    'sena',    'sent',    'sera',    'seta',    'snar',    'star',    'sten',
    'tace',    'taes',    'tane',    'tans',    'tare',    'tarn',    'tars',
    'tear',    'teas',    'tecs',    'tens',    'tern',    'tres',    'tsar',
    'ace',     'act',     'ane',     'ans',     'ant',     'arc',     'are',
    'ars',     'art',     'ate',     'ats',     'can',     'car',     'cat',
    'ean',     'ear',     'eas',     'eat',     'ens',     'era',     'ern',
    'ers',     'est',     'eta',     'nae',     'nas',     'nat',     'net',
    'ran',     'ras',     'rat',     'rec',     'ren',     'res',     'ret',
    'sac',     'sae',     'san',     'sar',     'sat',     'sea',     'sec',
    'sen',     'ser',     'set',     'tae',     'tan',     'tar',     'tas',
    'tea',     'tec',     'ten',     'tes'
  ]
  },{
    word:"parleys",
    solutions:['parleys', 'parsley', 'players', 'replays', 'sparely', 'lapser', 'layers',
    'lepras',  'parles',  'parley',  'payers',  'pearls',  'pearly', 'player',
    'plyers',  'rayles',  'relays',  'repays',  'replay',  'slayer', 'speary',
    'apers',   'apery',   'apres',   'arles',   'arsey',   'aryls',  'asper',
    'ayelp',   'ayres',   'earls',   'early',   'eyras',   'laers',  'lapse',
    'lares',   'laser',   'layer',   'leaps',   'lears',   'leary',  'lepra',
    'lerps',   'lyase',   'lyres',   'paler',   'pales',   'palsy',  'pares',
    'parle',   'parly',   'parse',   'payer',   'peals',   'pearl',  'pears',
    'pelas',   'plays',   'pleas',   'plyer',   'prase',   'prays',  'presa',
    'preys',   'pryse',   'pyral',   'pyres',   'rales',   'rapes',  'raspy',
    'rayle',   'reals',   'reaps',   'relay',   'repay',   'repla',  'reply',
    'resay',   'ryals',   'salep',   'sayer',   'sepal',   'seral',  'slyer',
    'slype',   'spaer',   'spale',   'spare',   'speal',   'spear',  'splay',
    'spray',   'spyal',   'spyre',   'yales',   'years',   'yelps',  'aery',
    'ales',    'alps',    'aper',    'apes',    'apse',    'ares',   'arle',
    'arse',    'arsy',    'aryl',    'ayes',    'ayre',    'earl',   'ears',
    'easy',    'eras',    'espy',    'eyas',    'eyra',    'laer',   'laps',
    'lare',    'lars',    'lase',    'lays',    'leap',    'lear',   'leas',
    'leps',    'lerp',    'leys',    'lyes',    'lyra',    'lyre',   'lyse',
    'pale',    'pals',    'paly',    'pare',    'pars',    'pase',   'pays',
    'peal',    'pear',    'peas',    'pela',    'pels',    'play',   'plea',
    'pray',    'prey',    'prys',    'pyas',    'pyes',    'pyre',   'rale',
    'rape',    'raps',    'rase',    'rasp',    'rays',    'real',   'reap',
    'rely',    'reps',    'ryal',    'ryas',    'ryes',    'rype',   'sale',
    'salp',    'seal',    'sear',    'sera',    'slae',    'slap',   'slay',
    'sley',    'spae',    'spar',    'spay',    'spry',    'sype',   'yale',
    'yaps',    'yare',    'year',    'yeas',    'yelp',    'yeps',   'ale',
    'alp',     'als',     'ape',     'are',     'ars',     'ary',    'asp',
    'aye',     'ays',     'ear',     'eas',     'els',     'era',    'ers',
    'lap',     'lar',     'las',     'lay',     'lea',     'lep',    'les',
    'ley',     'lye',     'pal',     'par',     'pas',     'pay',    'pea',
    'pel',     'per',     'pes',     'ply',     'pre',     'pry',    'pya',
    'pye',     'rap',     'ras',     'ray',     'rep',     'res',    'rya',
    'rye',     'sae',     'sal',     'sap',     'sar',     'say',    'sea',
    'sel',     'ser',     'sey',     'sly',     'spa',     'spy',    'sye',
    'yae',     'yap',     'yar',     'yea',     'yep',     'yes'
  ]
  },{
    word:"dearths",
    solutions:['dearths', 'hardest', 'hardset', 'hatreds', 'threads', 'trashed', 'dasher',
    'daters',  'dearth',  'deaths',  'derats',  'derths',  'earths',  'hasted',
    'haters',  'hatred',  'heards',  'hearts',  'rashed',  'shader',  'shared',
    'stared',  'steard',  'tashed',  'thread',  'trades',  'treads',  'arets',
    'arsed',   'ashed',   'ashet',   'aster',   'dares',   'darts',   'dater',
    'dates',   'dears',   'deash',   'death',   'derat',   'derth',   'drats',
    'drest',   'eards',   'earst',   'earth',   'hades',   'hadst',   'haets',
    'hards',   'hared',   'hares',   'harts',   'haste',   'hated',   'hater',
    'hates',   'heads',   'heard',   'hears',   'heart',   'heast',   'heats',
    'herds',   'rahed',   'rased',   'rated',   'rates',   'rathe',   'raths',
    'reads',   'reast',   'resat',   'rheas',   'sadhe',   'sared',   'sated',
    'shade',   'shard',   'share',   'shear',   'sherd',   'shred',   'stade',
    'stare',   'stead',   'stear',   'strad',   'strae',   'tahrs',   'tared',
    'tares',   'taser',   'teads',   'tears',   'tehrs',   'teras',   'thars',
    'thrae',   'trade',   'trads',   'trash',   'tread',   'tsade',   'ahed',
    'ards',    'ared',    'ares',    'aret',    'arse',    'arts',    'ates',
    'daes',    'dahs',    'dare',    'dart',    'dash',    'date',    'dear',
    'drat',    'eard',    'ears',    'east',    'eath',    'eats',    'edhs',
    'eras',    'erst',    'etas',    'eths',    'hade',    'hads',    'haed',
    'haes',    'haet',    'hard',    'hare',    'hart',    'hast',    'hate',
    'hats',    'head',    'hear',    'heat',    'herd',    'hers',    'hest',
    'hets',    'rade',    'rads',    'rahs',    'rase',    'rash',    'rast',
    'rate',    'rath',    'rats',    'read',    'reds',    'rehs',    'resh',
    'rest',    'rets',    'rhea',    'sade',    'sard',    'sate',    'sear',
    'seat',    'sera',    'seta',    'shad',    'shat',    'shea',    'shed',
    'shet',    'star',    'sted',    'tads',    'taed',    'taes',    'tahr',
    'tare',    'tars',    'tash',    'tead',    'tear',    'teas',    'teds',
    'tehr',    'thae',    'thar',    'trad',    'tres',    'tsar',    'ads',
    'ahs',     'ard',     'are',     'ars',     'art',     'ash',     'ate',
    'ats',     'dae',     'dah',     'das',     'ear',     'eas',     'eat',
    'edh',     'eds',     'ehs',     'era',     'ers',     'est',     'eta',
    'eth',     'had',     'hae',     'has',     'hat',     'her',     'hes',
    'het',     'rad',     'rah',     'ras',     'rat',     'red',     'reh',
    'res',     'ret',     'sad',     'sae',     'sar',     'sat',     'sea',
    'sed',     'ser',     'set',     'sha',     'she',     'tad',     'tae',
    'tar',     'tas',     'tea',     'ted',     'tes',     'the'
  ]
  },{
    word:"esprits",
    solutions:['esprits', 'persist', 'priests', 'sitreps', 'spriest', 'sprites', 'stirpes',
    'stripes', 'tripses', 'esprit',  'pierst',  'pierts',  'pisser',  'pistes',
    'prests',  'priest',  'prises',  'reists',  'resist',  'resits',  'ripest',
    'sister',  'sitrep',  'speirs',  'sperst',  'spiers',  'spires',  'spirts',
    'spites',  'sprite',  'sprits',  'stipes',  'stires',  'stirps',  'streps',
    'stripe',  'strips',  'tripes',  'epris',   'peris',   'perst',   'perts',
    'pests',   'petri',   'piers',   'piert',   'piets',   'pises',   'piste',
    'press',   'prest',   'pries',   'prise',   'priss',   'reist',   'resit',
    'rests',   'ripes',   'rises',   'risps',   'rites',   'seirs',   'septs',
    'sipes',   'sires',   'sites',   'speir',   'spets',   'spier',   'spies',
    'spire',   'spirt',   'spite',   'spits',   'sprit',   'steps',   'sties',
    'stipe',   'stire',   'stirp',   'stirs',   'strep',   'strip',   'tiers',
    'tires',   'tress',   'tries',   'tripe',   'trips',   'erst',    'ests',
    'ires',    'peri',    'pert',    'pest',    'pets',    'pier',    'pies',
    'piet',    'pirs',    'pise',    'piss',    'pits',    'psis',    'psst',
    'reis',    'reps',    'rest',    'rets',    'ripe',    'rips',    'ript',
    'rise',    'risp',    'rite',    'rits',    'seir',    'seis',    'seps',
    'sept',    'sers',    'sets',    'sies',    'sipe',    'sips',    'sire',
    'sirs',    'sist',    'site',    'sits',    'spet',    'spie',    'spit',
    'sris',    'step',    'stie',    'stir',    'tier',    'ties',    'tips',
    'tire',    'tres',    'trie',    'trip',    'ers',     'ess',     'est',
    'ire',     'its',     'per',     'pes',     'pet',     'pie',     'pir',
    'pis',     'pit',     'pre',     'psi',     'pst',     'rei',     'rep',
    'res',     'ret',     'rip',     'rit',     'sei',     'ser',     'set',
    'sip',     'sir',     'sis',     'sit',     'sri',     'tes',     'tie',
    'tip',     'tis'
  ]
  },{
    word:"earnest",
    solutions:[ 'earnest', 'eastern', 'nearest', 'rateens', 'antres', 'arenes', 'aretes',
    'astern',  'easter',  'eaters',  'enates',  'ensate', 'ensear', 'entera',
    'enters',  'neater',  'nester',  'ranees',  'rateen', 'reates', 'renest',
    'rentes',  'reseat',  'resent',  'saeter',  'sateen', 'seater', 'senate',
    'steane',  'steare',  'sterna',  'strene',  'teaser', 'tenser', 'ternes',
    'transe',  'treens',  'antes',   'antre',   'arene',  'arete',  'arets',
    'aster',   'earns',   'earst',   'easer',   'eaten',  'eater',  'enate',
    'enter',   'erase',   'ernes',   'ester',   'etens',  'etnas',  'nares',
    'nates',   'nears',   'neats',   'nerts',   'netes',  'ranee',  'rants',
    'rates',   'reans',   'reast',   'reate',   'reens',  'reest',  'rente',
    'rents',   'resat',   'reset',   'saner',   'saree',  'seare',  'sente',
    'setae',   'snare',   'sneer',   'stane',   'stare',  'starn',  'stean',
    'stear',   'steen',   'steer',   'stere',   'stern',  'strae',  'tares',
    'tarns',   'taser',   'tears',   'tease',   'teens',  'teers',  'tenes',
    'tense',   'teras',   'teres',   'terne',   'terns',  'terse',  'trans',
    'treen',   'trees',   'anes',    'ante',    'ants',   'ares',   'aret',
    'arse',    'arts',    'ates',    'eans',    'earn',   'ears',   'ease',
    'east',    'eats',    'enes',    'eras',    'eres',   'erne',   'erns',
    'erst',    'esne',    'etas',    'eten',    'etna',   'nare',   'nats',
    'near',    'neat',    'nest',    'nete',    'nets',   'rant',   'rase',
    'rast',    'rate',    'rats',    'rean',    'reen',   'rees',   'rens',
    'rent',    'rest',    'rete',    'rets',    'sane',   'sant',   'sate',
    'sean',    'sear',    'seat',    'seen',    'seer',   'sena',   'sene',
    'sent',    'sera',    'sere',    'seta',    'snar',   'snee',   'star',
    'sten',    'taes',    'tane',    'tans',    'tare',   'tarn',   'tars',
    'tear',    'teas',    'teen',    'teer',    'tees',   'tene',   'tens',
    'tern',    'tree',    'tres',    'tsar',    'ane',    'ans',    'ant',
    'are',     'ars',     'art',     'ate',     'ats',    'ean',    'ear',
    'eas',     'eat',     'een',     'ene',     'ens',    'era',    'ere',
    'ern',     'ers',     'est',     'eta',     'nae',    'nas',    'nat',
    'nee',     'net',     'ran',     'ras',     'rat',    'ree',    'ren',
    'res',     'ret',     'sae',     'san',     'sar',    'sat',    'sea',
    'see',     'sen',     'ser',     'set',     'tae',    'tan',    'tar',
    'tas',     'tea',     'tee',     'ten',     'tes'
  ]
  },{
    word:"potters",
    solutions:['potters', 'protest', 'spotter', 'opters', 'otters', 'poster', 'potter',
    'presto',  'repost',  'repots',  'respot', 'rottes', 'stoper', 'topers',
    'tortes',  'toters',  'tropes',  'estop',  'estro',  'opter',  'otter',
    'perst',   'perts',   'pesto',   'petto',  'poets',  'pores',  'ports',
    'poser',   'potes',   'potts',   'prest',  'prose',  'prost',  'repos',
    'repot',   'resto',   'ropes',   'roset',  'rotes',  'rotte',  'spore',
    'sport',   'stept',   'stoep',   'stope',  'stopt',  'store',  'strep',
    'strop',   'terts',   'toper',   'topes',  'tores',  'torse',  'torte',
    'torts',   'toter',   'totes',   'trest',  'trets',  'trope',  'trots',
    'epos',    'eros',    'erst',    'opes',   'opts',   'ores',   'orts',
    'pert',    'peso',    'pest',    'pets',   'poet',   'pore',   'port',
    'pose',    'post',    'pote',    'pots',   'pott',   'pros',   'reos',
    'repo',    'reps',    'rest',    'rets',   'roes',   'rope',   'rose',
    'rost',    'rote',    'rots',    'sept',   'sett',   'sore',   'sort',
    'spet',    'spot',    'step',    'stet',   'stop',   'stot',   'test',
    'tets',    'toes',    'tope',    'tops',   'tore',   'tors',   'tort',
    'tose',    'tost',    'tote',    'tots',   'tres',   'tret',   'trop',
    'trot',    'ers',     'est',     'oes',    'ope',    'ops',    'opt',
    'ore',     'ors',     'ort',     'ose',    'per',    'pes',    'pet',
    'pos',     'pot',     'pre',     'pro',    'pst',    'reo',    'rep',
    'res',     'ret',     'roe',     'rot',    'ser',    'set',    'sop',
    'sot',     'tes',     'tet',     'toe',    'top',    'tor',    'tot'
  ]
  },{
    word:"aligned",
    solutions:['aligned', 'dealing', 'leading', 'alined', 'angled', 'daeing', 'dangle',
    'denial',  'dingle',  'elding',  'engild', 'gained', 'genial', 'gilden',
    'lading',  'lagend',  'ligand',  'linage', 'nailed', 'agile',  'ailed',
    'algid',   'algin',   'alien',   'align',  'aline',  'angel',  'angle',
    'anile',   'daine',   'deign',   'diane',  'dinge',  'elain',  'eland',
    'eldin',   'eliad',   'gelid',   'genal',  'glade',  'gland',  'glean',
    'glide',   'ideal',   'ingle',   'laden',  'lande',  'liane',  'liang',
    'ligan',   'ligne',   'lined',   'linga',  'naled',  'nidal',  'aged',
    'agen',    'agin',    'aide',    'aine',   'anil',   'dale',   'dali',
    'dang',    'deal',    'dean',    'deil',   'deli',   'deni',   'dial',
    'diel',    'dine',    'ding',    'egad',   'egal',   'eild',   'eina',
    'elan',    'gade',    'gadi',    'gaed',   'gaen',   'gaid',   'gain',
    'gale',    'gane',    'geal',    'gean',   'geld',   'gena',   'gied',
    'gien',    'gila',    'gild',    'glad',   'gled',   'glei',   'glen',
    'glia',    'glid',    'idea',    'idle',   'igad',   'ilea',   'lade',
    'laid',    'lain',    'land',    'lane',   'lang',   'lead',   'lean',
    'lend',    'leng',    'lied',    'lien',   'lind',   'line',   'ling',
    'nail',    'neal',    'ngai',    'nide',   'nied',   'age',    'aid',
    'ail',     'ain',     'ale',     'and',    'ane',    'ani',    'dae',
    'dag',     'dal',     'dan',     'deg',    'dei',    'del',    'den',
    'die',     'dig',     'din',     'ean',    'eld',    'end',    'eng',
    'gad',     'gae',     'gal',     'gan',    'ged',    'gel',    'gen',
    'gid',     'gie',     'gin',     'ide',    'ing',    'lad',    'lag',
    'lea',     'led',     'leg',     'lei',    'lid',    'lie',    'lig',
    'lin',     'nae',     'nag',     'ned',    'neg',    'nid',    'nie',
    'nil'
  ]
  },
];

export default anagrams